export const ADD_HOTELS = 'ADD_HOTELS';
export const HOTELS_LOADING = 'HOTELS_LOADING';
export const HOTELS_FAILED = 'HOTELS_FAILED';
export const ADD_PRICES = 'ADD_PRICES';
export const PRICES_LOADING = 'PRICES_LOADING';
export const PRICES_FAILED = 'PRICES_FAILED';
export const SET_CURRENCY = 'SET_CURRENCY';